# Generated by Django 4.2.25 on 2025-11-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
