# Generated by Django 4.2.25 on 2025-11-02 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0007_partnerspace_payout_per_checkin_ngn_and_more'),
        ('users', '0002_customuser_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='managed_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='spaces.partnerspace'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('SUBSCRIBER', 'Subscriber'), ('PARTNER', 'Partner')], default='SUBSCRIBER', max_length=20),
        ),
    ]
