# Generated by Django 4.2.25 on 2025-11-02 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('users', '0003_customuser_managed_space_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('SUBSCRIBER', 'Subscriber'), ('PARTNER', 'Partner'), ('TEAM_ADMIN', 'Team Admin'), ('TEAM_MEMBER', 'Team Member')], default='SUBSCRIBER', max_length=20),
        ),
    ]
