# Generated by Django 4.2.25 on 2025-11-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerspace',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated list of amenities'),
        ),
    ]
