# Generated by Django.

from django.db import migrations

def load_spaces(apps, schema_editor):
    """
    Loads the initial list of partner spaces into the database.
    """
    PartnerSpace = apps.get_model('spaces', 'PartnerSpace')
    
    # --- THIS IS THE FIX ---
    # Instead of Plan.AccessTier.STANDARD, we use the raw string value.
    standard_tier = 'STANDARD'
    
    SPACES_DATA = [
        {
            "name": "Seb’s Hub Co-Working Space",
            "address": "No 32, Awolowo Avenue, Bodija, Ibadan, Oyo State, Nigeria",
            "amenities": "AC, Kitchen, Meeting Rooms, Power Backup, Private Offices, Wi-Fi",
        },
        {
            "name": "Worknub Co-working Space",
            "address": "West One Building, beside the office of the governor's wife, Agodi GRA, Ibadan.",
            "amenities": "AC, Kitchen, Meeting Rooms, Power Backup, Private Offices, Wi-Fi",
        },
        {
            "name": "Stargate Workstation",
            "address": "9th Floor, Cocoa House, Dugbe, Ibadan, Oyo State, Nigeria",
            "amenities": "AC, Private Offices, Wi-Fi",
        },
        {
            "name": "theBUNKer Services Nigeria Limited",
            "address": "Ibadan", # As provided
            "amenities": "AC, Kitchen, Meeting Rooms, Power Backup, Private Offices, Wi-Fi",
        },
        {
            "name": "Nesta Co-work Space, Akobo",
            "address": "House 10, Road 17, Bashorun Estate, Akobo, Ibadan",
            "amenities": "Kitchen, Meeting Rooms, Power Backup, Private Offices, Wi-Fi",
        },
        {
            "name": "Cyberhaven",
            "address": "Okunmade street, opposite veterinary junction",
            "amenities": "AC, Meeting Rooms, Wi-Fi",
        },
        {
            "name": "Atelier Coworking Space & French Café",
            "address": "Ibadan, Oyo State",
            "amenities": "AC, Power Backup, Wi-Fi",
        },
    ]

    for space_data in SPACES_DATA:
        # Use get_or_create to avoid creating duplicates if we run this again
        PartnerSpace.objects.get_or_create(
            name=space_data["name"],
            defaults={
                'address': space_data["address"],
                'amenities': space_data["amenities"],
                'access_tier': standard_tier,
            }
        )

def unload_spaces(apps, schema_editor):
    """
    Removes the spaces. We'll just delete them all based on the names.
    """
    PartnerSpace = apps.get_model('spaces', 'PartnerSpace')
    
    # Get just the names from the data
    SPACES_DATA = [
        # (Copied from above just to make this function self-contained)
        { "name": "Seb’s Hub Co-Working Space" },
        { "name": "Worknub Co-working Space" },
        { "name": "Stargate Workstation" },
        { "name": "theBUNKer Services Nigeria Limited" },
        { "name": "Nesta Co-work Space, Akobo" },
        { "name": "Cyberhaven" },
        { "name": "Atelier Coworking Space & French Café" },
    ]
    space_names = [d["name"] for d in SPACES_DATA]
    
    # Delete only the spaces we added
    PartnerSpace.objects.filter(name__in=space_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_partnerspace_amenities'), # Make sure this matches your PREVIOUS migration
    ]

    operations = [
        migrations.RunPython(load_spaces, reverse_code=unload_spaces),
    ]

