# Generated by Django.

from django.db import migrations

def load_plans(apps, schema_editor):
    """
    Loads the initial 3 pilot plans into the database.
    """
    Plan = apps.get_model('spaces', 'Plan')

    # Use the raw string values for the tiers
    STANDARD_TIER = 'STANDARD'
    ALL_TIER = 'ALL'

    PLANS_DATA = [
        {
            "name": "Flex Basic",
            "price_ngn": 22500,
            "included_days": 8,
            "access_tier": STANDARD_TIER,
        },
        {
            "name": "Flex Pro",
            "price_ngn": 45000,
            "included_days": 16,
            "access_tier": ALL_TIER,
        },
        {
            "name": "Flex Unlimited",
            "price_ngn": 75000,
            "included_days": 999, # Using 999 to represent Unlimited
            "access_tier": ALL_TIER,
        },
    ]

    for plan_data in PLANS_DATA:
        Plan.objects.get_or_create(
            name=plan_data["name"],
            defaults={
                'price_ngn': plan_data["price_ngn"],
                'included_days': plan_data["included_days"],
                'access_tier': plan_data["access_tier"],
            }
        )

def unload_plans(apps, schema_editor):
    """
    Removes the 3 pilot plans.
    """
    Plan = apps.get_model('spaces', 'Plan')
    plan_names = [d["name"] for d in PLANS_DATA]
    Plan.objects.filter(name__in=plan_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_load_initial_spaces'), # <-- Make sure this matches your PREVIOUS migration
    ]

    operations = [
        migrations.RunPython(load_plans, reverse_code=unload_plans),
    ]

