# Generated by Django.

from django.db import migrations
from django.db import models # <-- THIS IS THE MISSING LINE

def update_tiers(apps, schema_editor):
    """
    Updates 'ALL' tier plans to the new 'PREMIUM' tier.
    """
    Plan = apps.get_model('spaces', 'Plan')
    
    Plan.objects.filter(access_tier='ALL').update(access_tier='PREMIUM')
    
    Plan.objects.filter(name__in=["Flex Pro", "Flex Unlimited"]).update(access_tier='PREMIUM')

def revert_tiers(apps, schema_editor):
    """
    Reverts 'PREMIUM' plans back to 'ALL'.
    """
    Plan = apps.get_model('spaces', 'Plan')
    Plan.objects.filter(access_tier='PREMIUM').update(access_tier='ALL')


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_checkintoken'), # <-- This should be your previous migration
    ]

    operations = [
        # This migration handles the DB-level change (ALTER COLUMN)
        migrations.AlterField(
            model_name='plan',
            name='access_tier',
            field=models.CharField(choices=[('STANDARD', 'Standard Spaces'), ('PREMIUM', 'All Spaces (Standard + Premium)')], default='STANDARD', max_length=20),
        ),
        # This migration handles the data change (UPDATE table)
        migrations.RunPython(update_tiers, reverse_code=revert_tiers),
    ]
