# Generated by Django 4.2.25 on 2025-11-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_update_plan_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerspace',
            name='payout_per_checkin_ngn',
            field=models.DecimalField(decimal_places=2, default=1500.0, help_text='Amount (NGN) paid to partner per check-in', max_digits=10),
        ),
        migrations.AlterField(
            model_name='partnerspace',
            name='access_tier',
            field=models.CharField(choices=[('STANDARD', 'Standard Spaces'), ('PREMIUM', 'All Spaces (Standard + Premium)')], default='STANDARD', max_length=20),
        ),
    ]
