# Generated by Django 4.2.25 on 2026-03-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0010_partnerspace_is_active_partnerspace_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='included_days',
            field=models.PositiveIntegerField(help_text='Number of days included per month. Use 30 for unlimited.'),
        ),
    ]
